apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-proxy-conf
data:
  # Default password is 'total.apple.silk'
  .htpasswd: |
    admin:$apr1$BKQlWOsd$P5PO8l.j1hFDQZ2J.tVQj1
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus
#   annotations:
#     prometheus.io/scrape: 'true'
#     prometheus.io/port:   '9099'
# spec:
#   # For testing, we expose prometheus publicly
#   # Go to http://<ip>/prometheus to access it
#   type: LoadBalancer
