{
 "title": "Indexing Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Subgraph Block vs. Network Block",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect\n  g.name || (case\n        when g.pending_version = v.id then ' (P)'\n        when g.current_version = v.id then ' (C)'\n        else ' (U)' end) as subgraph_name,\n  d.id as deployment,\n  s.id as schema,\n  replace(a.node_id, 'index_node_','') as nodeId,\n  d.synced::text,\n  n.name as network,\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network,\n  (case when n.name = 'mainnet' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\n        when n.name = 'rinkeby' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\n        when n.name = 'kovan' then ((n.head_block_number - d.latest_ethereum_block_number)/15)::text\n        when n.name = 'poa-core' then ((n.head_block_number - d.latest_ethereum_block_number)/12)::text\n        else 'ø' end) as lag\nfrom subgraphs.subgraph_deployment as d,\n     subgraphs.subgraph_deployment_assignment as a,\n     subgraphs.subgraph_version as v,\n     subgraphs.subgraph as g,\n     subgraphs.ethereum_contract_data_source as ds,\n     subgraphs.subgraph_manifest m,\n     ethereum_networks  as n,\n     deployment_schemas as s\nwhere g.id = v.subgraph\n  and v.id in (g.pending_version, g.current_version)\n  and a.id = d.id\n  and m.id = d.manifest \n  and ds.id = m.data_sources[1]\n  and s.subgraph = d.id\n  and v.deployment = d.id\n  and not d.failed\n  and n.name = ds.network\norder by blocks_behind_network desc, subgraph_name;"
    }
   ]
  },
  {
   "title": "Fatal errors",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  vid, block_number, subgraph_id, message, handler\nFROM subgraphs.subgraph_error\nORDER BY vid DESC"
    }
   ]
  },
  {
   "title": "Subgraph Node Assignments",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select replace(node_id, 'index_node_', '') as nodeId,\n       count(*) as num_assigned,\n       array_agg(id) as deployments\n  from subgraphs.subgraph_deployment_assignment\n group by node_id\n order by node_id asc;\n"
    }
   ]
  },
  {
   "title": "Network Head Blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  name,\n  head_block_number AS \"block_number\",\n  head_block_hash AS \"block_hash\"\nFROM ethereum_networks\nORDER BY name;"
    }
   ]
  },
  {
   "title": "Deployed subgraphs that have not started",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select now() as time, count(*) as num_subgraphs\n   from (\n   select d.id, d.latest_ethereum_block_number block\n     from subgraphs.subgraph_deployment d,\n          subgraphs.subgraph_deployment_assignment a\n    where d.id = a.id\n    and not d.failed) a\n   where a.block < 100;\n"
    }
   ]
  }
 ]
}
{
 "title": "Subgraph Indexing Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "select subgraph from deployment_schemas where id > 0"
   },
   {
    "name": "handler",
    "query": "label_values(deployment_handler_execution_time_bucket{deployment=\"[[deployment]]\"}, handler)"
   },
   {
    "name": "host_fn",
    "query": "label_values(deployment_host_fn_execution_time_bucket{deployment=\"[[deployment]]\"}, host_fn_name)"
   },
   { "name": "network", "query": "ethereum_chain_head_number" }
  ]
 },
 "panels": [
  {
   "title": "Time spent while indexing",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\"}[1y]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"unknown\"}[1y]))",
     "legendFormat": "unknown"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"scan_blocks\"}[1y]))",
     "legendFormat": "scan_blocks"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"module_init\"}[1y]))",
     "legendFormat": "module_init"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"run_handler\"}[1y]))",
     "legendFormat": "run_handler"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"transact_block\"}[1y]))",
     "legendFormat": "transact_block"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_other\"}[1y]))",
     "legendFormat": "host_export_other"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_store_get\"}[1y]))",
     "legendFormat": "host_export_store_get"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_store_set\"}[1y]))",
     "legendFormat": "host_export_store_set"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_ethereum_call\"}[1y]))",
     "legendFormat": "host_export_ethereum_call"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_ipfs_cat\"}[1y]))",
     "legendFormat": "host_export_ipfs_cat"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"host_export_ipfs_map\"}[1y]))",
     "legendFormat": "host_export_ipfs_map"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"store_get_asc_new\"}[1y]))",
     "legendFormat": "store_get_asc_new"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"apply_entity_modifications\"}[1y]))",
     "legendFormat": "apply_entity_modifications"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"check_interface_entity_uniqueness\"}[1y]))",
     "legendFormat": "check_interface_entity_uniqueness"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"apply_entity_modifications_update\"}[1y]))",
     "legendFormat": "apply_entity_modifications_update"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"apply_entity_modifications_insert\"}[1y]))",
     "legendFormat": "apply_entity_modifications_insert"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"as_modifications\"}[1y]))",
     "legendFormat": "as_modifications"
    },
    {
     "expr": "sum(increase(deployment_sync_secs{deployment=\"[[deployment]]\",section=\"entity_cache_evict\"}[1y]))",
     "legendFormat": "entity_cache_evict"
    }
   ]
  },
  {
   "title": "Eth Rpc Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_eth_rpc_request_duration{deployment=\"[[deployment]]\"}[1m])) by (method) * 1000",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Last Reverted Block Number",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(deployment_reverted_blocks{deployment=\"[[deployment]]\"}[1m])",
     "legendFormat": "number of reverted blocks"
    },
    {
     "expr": "deployment_reverted_blocks{deployment=\"[[deployment]]\"}",
     "legendFormat": "last reverted block number"
    }
   ]
  },
  {
   "title": "Total time waiting for DB connection",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "deployment_get_entity_conn_secs{deployment=\"subgraphs\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "<br/> \n<center> \n  <h1>Block Processing / Handler Execution</h1> \n</center>"
   },
   "content": "<br/> \n<center> \n  <h1>Block Processing / Handler Execution</h1> \n</center>"
  },
  {
   "title": "Blocks Processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_block_processing_duration_sum{deployment=\"[[deployment]]\"}[1m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Block Processing Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(deployment_block_processing_duration_bucket{deployment=\"[[deployment]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Transact Block Ops Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(deployment_transact_block_operations_duration_bucket{deployment=\"[[deployment]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "[[host_fn]] Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(deployment_host_fn_execution_time_bucket{deployment=\"[[deployment]]\",host_fn_name=\"[[host_fn]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Host Function Triggered",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_host_fn_execution_time_sum{deployment=\"[[deployment]]\"}[1m])) by (host_fn_name)",
     "legendFormat": "{{host_fn_name}}"
    }
   ]
  },
  {
   "title": "Block Trigger Count",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(deployment_block_trigger_count_bucket{deployment=\"[[deployment]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "[[handler]] Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(increase(deployment_handler_execution_time_bucket{deployment=\"[[deployment]]\",handler=\"[[handler]]\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Handler Triggered",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(deployment_handler_execution_time_sum{deployment=\"[[deployment]]\"}[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 64 },
   "options": {
    "content": "</br>\n<center> \n  <h1>GraphQL Server</h1> \n</center>"
   },
   "content": "</br>\n<center> \n  <h1>GraphQL Server</h1> \n</center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 64 },
   "options": {
    "content": "<br/> \n<center> \n  <h1>Block Ingestor</h1> \n</center>"
   },
   "content": "<br/> \n<center> \n  <h1>Block Ingestor</h1> \n</center>"
  },
  {
   "title": "Query Execution Time Histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(query_execution_time_bucket{deployment=\"[[deployment]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query Execution Time Histogram ([[deployment]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 66 },
   "repeat": "deployment",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(query_execution_time_bucket{deployment=\"[[deployment]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "type": "table-old",
   "description": "block_ingestor_panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "targets": [
    { "expr": "ethereum_chain_head_number{}", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "Block Syncing Rate",
   "type": "graph",
   "description": "block_ingestor_panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ethereum_chain_head_number{kubernetes_pod_name=\"index-node-0\"}[1m])) by (network)",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Queries  (All Subgraphs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(query_execution_time_count[1m])) by (deployment)",
     "legendFormat": "{{subgraph_deployment}}"
    }
   ]
  },
  {
   "title": "Query Rate (All Subgraphs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "locale", "label": "Queries per minute" }
   ],
   "targets": [
    {
     "expr": "sum(rate(query_execution_time_count[1m])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Failed Queries  (All Subgraphs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "increase(query_failed_execution_time_count[1m])",
     "legendFormat": "{{subgraph_deployment}}"
    }
   ]
  }
 ]
}
{
 "title": "Postgres Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect application_name,\n       extract(epoch from age(now(), xact_start)) as age,\n       query from pg_stat_activity\n where query not like '%grafana ignore%'\n   and state='active'\norder by query_start desc"
    }
   ]
  },
  {
   "title": "Transactions until wraparound vacuum",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nSELECT\n  relname as table,\n  least((SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_freeze_max_age') - age(relfrozenxid), \n        (SELECT setting::int FROM pg_settings WHERE name = 'autovacuum_multixact_freeze_max_age') - mxid_age(relminmxid))\n        tx_before_wraparound_vacuum,\n  pg_stat_get_last_autovacuum_time(c.oid) AS last_autovacuum,\n  age(relfrozenxid) AS xid_age,\n  mxid_age(relminmxid) AS mxid_age\nFROM\n  pg_class c\nWHERE\n  c.relname in ('ethereum_blocks', 'eth_call_cache','subgraph_deployment')\n  and c.relfrozenxid != 0\n"
    }
   ]
  },
  {
   "title": "Autovacuum pressure",
   "type": "table",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect count(*) as tables_needing_vacuum,\n       -min(tx_before_wraparound_vacuum) as txns_past,\n       min(last_autovacuum) as last_autovacuum\n  from (\n    select oid::regclass::text AS table,\n       least(\n         (select setting::int\n            from pg_settings\n            where name = 'autovacuum_freeze_max_age') - age(relfrozenxid),\n         (select setting::int\n            from pg_settings\n           where name = 'autovacuum_multixact_freeze_max_age')\n                - mxid_age(relminmxid)) as tx_before_wraparound_vacuum,\n       pg_stat_get_last_autovacuum_time(oid) AS last_autovacuum,\n       age(relfrozenxid) AS xid_age,\n       mxid_age(relminmxid) AS mxid_age\n  from pg_class\n where relfrozenxid != 0\n   and oid > 16384\n   and relkind='r') a where a.tx_before_wraparound_vacuum < 0;\n"
    }
   ]
  },
  {
   "title": "Active locks",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nSELECT  a.application_name,\n        coalesce(extract(epoch from age(now(), a.xact_start)), 0) as age,\n        l.relation::regclass,\n        l.mode,\n        l.GRANTED::varchar,\n        l.locktype \"Target\"\nFROM pg_stat_activity a\nJOIN pg_locks l ON l.pid = a.pid\nwhere pg_backend_pid() != a.pid\norder by granted asc, age desc;"
    }
   ]
  },
  {
   "title": "Idle transactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\nselect client_addr,\n       application_name,\n       usename,\n       state,\n       extract(epoch from age(now(), xact_start)) as age\n  from pg_stat_activity\n where query not like '%grafana ignore%'\n   and state like '%idle in transaction%'\norder by query_start desc"
    }
   ]
  }
 ]
}