apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: query-node-backend-config
spec:
  # Use a long timeout for WebSocket connections
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 0
