apiVersion: v1
kind: Service
metadata:
  name: query-node
  annotations:
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"80":{}}}'
spec:
  type: LoadBalancer
  selector:
    app: query-node
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
